# Default configuration map for provisioning the GraphDB jolokia access settings.
# To change it, prepare another configuration map and update "graphdb.configs.jolokiaAccessConfigMap"
{{- $configs := (.Values.graphdb.configs | default dict) }}
{{- if $configs.jolokiaAccessConfigMap }}
{{- if eq $configs.jolokiaAccessConfigMap "graphdb-jolokia-access-configmap" }}
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-jolokia-access-configmap
  labels:
    name: graphdb-jolokia-access-configmap
data:
  jolokia-access.xml: |-
{{ tpl (.Files.Get "files/config/jolokia-access.xml" | indent 4) . }}
{{- end }}
{{- end }}
