# Default configuration map for provisioning GraphDB repository.
# To change it, prepare another configuration map and update "graphdb.repositoryConfigmap"
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-settings-default-configmap
  labels:
    name: graphdb-settings-default-configmap
data:
  settings.js: |-
{{ tpl (.Files.Get "files/config/settings.js" | indent 4) . }}
  graphdb.properties: |-
{{ tpl (.Files.Get "files/config/graphdb.properties" | indent 4) . }}
