{{ if ne .Values.graphdb.topology "standalone" }}
{{ range $i, $worker_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.workersCount | int) 1 }}
---
apiVersion: {{ $.Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-worker-{{ $worker_index }}-configmap
  labels:
    name: graphdb-worker-{{ $worker_index }}-configmap
data:
  # >- means replace new line with space and no new lines at the end
  GDB_JAVA_OPTS: >-
    -Denable-context-index=true
    -Dentity-pool-implementation=transactional
    -Dhealth.max.query.time.seconds=60
    -Dgraphdb.vhosts={{ $.Values.deployment.protocol }}://{{ $.Values.deployment.host }}{{ $.Values.graphdb.workbench.subpath }}-worker-{{ $worker_index }}
    -Dgraphdb.append.request.id.headers=true
    -Dgraphdb.auth.token.secret={{ $.Values.graphdb.clusterConfig.clustersecret | quote }}
    {{ default $.Values.graphdb.workers.java_args (include "resolveWorkerValue" (dict "nodes" $.Values.graphdb.workers.nodes "value_name" "java_args" "worker_index" $worker_index )) }}
{{ end }}
{{ end }}
